---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: 'app=accesscontrol-service'
    backstage.io/techdocs-ref: dir:./access-control
    harness.io/project-url: https://stage.harness.io/ng/#/account/wFHXHD0RRQWoO8tIZT5YVw/ci/orgs/Harness/projects/RELEASEBUILDS/dashboard
    harness.io/ci-pipelineIds: AccessControlUBISaaSReleaseBuild,cutAccessControlRelease,AccessControlUBIOnPremReleaseBuild 
    github.com/project-slug: sandeepa-kv-jois/harness-core
    github.com/project-readme-path: access-control/README.md
  name: access-control
  tags:
    - java
spec:
  lifecycle: production
  system: CD-NG 
  owner: pl-access-eng
  type: service
  providesApis:
    - access-control
  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: 'app=platform-service'
    backstage.io/techdocs-ref: dir:./platform-service
    harness.io/project-url: https://stage.harness.io/ng/#/account/wFHXHD0RRQWoO8tIZT5YVw/ci/orgs/Harness/projects/RELEASEBUILDS/dashboard
    harness.io/ci-pipelineIds: PlatformServiceUBISaaSReleaseBuild,CutPlatformServiceReleaseBranch,PlatformServiceUBIOnPremReleaseBuild
    github.com/project-slug: sandeepa-kv-jois/harness-core
    github.com/project-readme-path: platform-service/README.md 
  name: platform-service
  tags:
    - java   
spec:
  lifecycle: production
  system: CD-NG
  owner: pl-eng
  type: service
  providesApis:
    - platform-service 
