---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: 'app=accesscontrol-service'
    github.com/project-slug: 'harness/harness-core/'
    backstage.io/techdocs-ref: dir:./access-control
  name: access-control
spec:
  lifecycle: production
  system: CD-NG,CI 
  owner: pl-team
  type: service
  providesApis:
    - access-control
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: 'app=platform-service'
    github.com/project-slug: 'harness/harness-core/tree/develop/platform-service'
    backstage.io/techdocs-ref: dir:./platform-service
  name: platform-service
spec:
  lifecycle: production
  system: CD-NG,CI
  owner: pl-engg
  type: service
  providesApis:
    - platform-service
