---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "production"
  owner: "idpui"
  system: "IDP_UI"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "idpapp"
  tags: [javascript]
  description: IDP microfrontend which has both Backstage UI and Backend components
  annotations:
    harness.io/ci-pipelineIds: test_aws
    harness.io/project-url: "https://app.harness.io/ng/account/wFHXHD0RRQWoO8tIZT5YVw/cd/orgs/default/projects/pragyesh_project/deployments"
    jira/project-key: IDP
    github.com/project-slug: harness/harness-idp
    backstage.io/source-location: 'url:https://github.com/harness/harness-idp/tree/main'
    backstage.io/techdocs-ref: 'url:https://github.com/harness/harness-idp/tree/docs'
    pagerduty.com/service-id: PS5XKY7
