apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: harness
  description: Everything related to harness-repo
  tags:
    - portal
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: Team-A
  domain: harness
