server:
  rootPath: /ccmevent
  applicationConnectors:
    - type: http
      port: 7280
    - type: https
      port: 7281
      keyStorePath: keystore.jks
      keyStorePassword: password
  adminConnectors:
    - type: http
      port: 8191

logging:
  level: INFO
  loggers:
    org.glassfish.jersey: INFO
    allbegray.slack: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"
    - type: gke-console
      threshold: TRACE
      target: STDOUT
      stackdriverLogEnabled: false

connectors:
  - port: 9890
    secure: true
    keyFilePath: key.pem
    certFilePath: cert.pem
  - port: 9889
harness-mongo:
  uri: mongodb://localhost:27017/harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  socketTimeout: 360000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO
  aliasDBName: harness

events-mongo:
  uri: mongodb://localhost:27017/events
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  socketTimeout: 360000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO
  aliasDBName: events

secretsConfiguration:
  secretResolutionEnabled: false
  gcpSecretManagerProject: ccm-play

eventDataBatchQueryConfig:
  queryBatchSize: 4000
  enableBatchWrite: false
