apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: 'app=platform-service'
  name: platform-service
spec:
  lifecycle: production
  owner: @pl-engg
  type: service
  providesApis:
    - platform-service
