apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: access-control
  description: Everything related to access control
  tags:
    - portal
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: Team-A
  domain: access
